### ISSUE TITLE
Nerf Rodentia Speed

### ISSUE THREAD

**Issue by zelezniciar1** [Grimbly-Station/Grimbly-Station#104]
# Description

Nerf the max speed rodentia can move at. Possibly issues stacking with trait "Parkour Expert"

Needs more testing.
# Reproduction

# Media

![Example Screenshot](https://example.com/thisimageisntreal.png)

# Additional context

**Comment by CometVoid** [comment]
https://github.com/Grimbly-Station/Grimbly-Station/pull/105 

fixed in this pr. was caused by rodentia crawling being a 4.6x speed multiplier, which was fine with the original crawling speed.

**Comment by Tmanzxd** [comment]
Just merged the PR, closing this now.
