### ISSUE TITLE
AME Nerf revert

### ISSUE THREAD

**Issue by zelezniciar1** [Grimbly-Station/Grimbly-Station#16]
Description

    - set AME fuel jar size to 1000 once again
    - revert changes to AME power output curve

Reproduction

n/a

Screenshots

n/a

Additional context

- DeltaV-origin stations are optimized for longer-term AME use, unlike those on WizDen. This PR would increase power stability

**Comment by sleepyyapril** [comment]
Delta-v solved this in a recent merged commit [1629](https://github.com/DeltaV-Station/Delta-v/pull/1629)

**Comment by zelezniciar1** [comment]
Got it, how do we feel about increasing fuel container size to 1000 again?

**Comment by sleepyyapril** [comment]
Agreeable
