### ISSUE TITLE
Tenebra and CAWS-25 Jackdaw crash server upon firing

### ISSUE THREAD

**Issue by TwoDucksOnnaPlane** [Grimbly-Station/Grimbly-Station#39]
## Description

Server crashes upon firing either weapon, unsure if to put this here or on the deltav repo.
**Reproduction**

spawn a Tenebra or CAWS-25, fire them.
**Screenshots**

**Additional context**

https://pastebin.com/weqGBk8Y exception thrown, might be useful

**Comment by SsalamethVersaach** [comment]
Howdy, could you try it with Delta-V's code as well and see if the error thrown is the same? Thanks!

**Comment by TwoDucksOnnaPlane** [comment]
DeltaV issue, closing and reposting there
