### ISSUE TITLE
Rodentia table collision

### ISSUE THREAD

**Issue by sleepyyapril** [Grimbly-Station/Grimbly-Station#90]
# Description

Rodentia can walk over tables.

# Reproduction

1. Join Grimbly server.
2. Spawn as Rodentia.
3. Walk over tables.

# Expected behavior

1. Join Grimbly server.
2. Spawn as Rodentia.
3. Walk **into** tables, colliding.

# Media

![Overlay issue](https://github.com/user-attachments/assets/42be881c-435a-4631-9832-75506c5c9df8)

**Comment by SsalamethVersaach** [comment]
I will check this, but pretty sure the radial hitboxes are letting them get past slightly. Will need to see how the hitboxes are drawn

**Comment by CometVoid** [comment]
this is most likely caused by a weird interaction when simultaneously crawling and sneaking not updating their collision layer properly

**Comment by Tmanzxd** [comment]
I'm pretty sure disabling of Rodentia sneak fixed this right? I'd have to check in my own devenv.

**Comment by Tmanzxd** [comment]
This has been fixed a while ago, closing now.
